### ISSUE TITLE
May not work with Que 0.11.4?

### ISSUE THREAD

**Issue by llimllib** [statianzo/que-testing#1]
After installing que-testing, I get:

```
/Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/que-0.11.4/lib/que/job.rb:139:in `work': undefined method `cleanup!' for #<Que::Testing::Adapter:0x007fd825456de8> (NoMethodError)
        from /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/que-0.11.4/lib/que/worker.rb:80:in `block in work_loop'
        from /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/que-0.11.4/lib/que/worker.rb:75:in `loop'
        from /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/que-0.11.4/lib/que/worker.rb:75:in `work_loop'
        from /Users/llimllib/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/que-0.11.4/lib/que/worker.rb:19:in `block in initialize'
```

**Comment by statianzo** [comment]
Looks like the adapter shim needs a cleanup! method

**Comment by statianzo** [comment]
Fixed by #2

**Comment by lessless** [comment]
Still having it here!

```
Volumes/Data/lessless/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/que-0.12.0/lib/que/job.rb:169:in `work': undefined method `cleanup!' for #<Que::Testing::Adapter:0x007fe22ba39b38> (NoMethodError)
    from /Volumes/Data/lessless/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/que-0.12.0/lib/que/worker.rb:80:in `block in work_loop'
    from /Volumes/Data/lessless/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/que-0.12.0/lib/que/worker.rb:75:in `loop'
    from /Volumes/Data/lessless/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/que-0.12.0/lib/que/worker.rb:75:in `work_loop'
    from /Volumes/Data/lessless/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/que-0.12.0/lib/que/worker.rb:19:in `block in initialize'
```

**Comment by statianzo** [comment]
@lessless I hadn't cut a release. Just made one. Try out que-testing 0.2.0.
